spring:
  application:
    name: BookingCreelHouse
  datasource:
    url: jdbc:h2:file:./booking.db
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
  # Step 1a: Configure SSL with the certificate and private key
  ssl:
    bundle:
      pem:
        web:
          keystore:
            private-key: "base64:LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZzBXRkRROE9rak54QkZmRzQKS2l2TDZVWEE1RUxtaytxd1M1dkR0VEt2b1ltaFJBTkNBQVFIWU1DZExJVmZWcUV2WXRNV2d2RS9WdStGVDBYbwpvN0pEajlkVkpyMHRrcEg0UG9KRmRGa2dldkd2aVJaZTNSRk9XdXVuYjFsdmNqd2tlcUJzTkd5YQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg=="
            certificate: "base64:LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNKakNDQWMyZ0F3SUJBZ0lRQjZpWVh1ais0TnZHVzl0N2FYNm03VEFLQmdncWhrak9QUVFEQWpCMU1SNHcKSEFZRFZRUUtFeFZ0YTJObGNuUWdaR1YyWld4dmNHMWxiblFnUTBFeEpUQWpCZ05WQkFzTUhITmhhM1ZBYzJGcgpkUzFVYUdsdWExQmhaQzFGTVRRdFIyVnVMVGN4TERBcUJnTlZCQU1NSTIxclkyVnlkQ0J6WVd0MVFITmhhM1V0ClZHaHBibXRRWVdRdFJURTBMVWRsYmkwM01CNFhEVEkyTURReE5UQTVNek0wT0ZvWERUSTRNRGN4TlRBNU16TTAKT0Zvd1VERW5NQ1VHQTFVRUNoTWViV3RqWlhKMElHUmxkbVZzYjNCdFpXNTBJR05sY25ScFptbGpZWFJsTVNVdwpJd1lEVlFRTERCeHpZV3QxUUhOaGEzVXRWR2hwYm10UVlXUXRSVEUwTFVkbGJpMDNNRmt3RXdZSEtvWkl6ajBDCkFRWUlLb1pJemowREFRY0RRZ0FFQjJEQW5TeUZYMWFoTDJMVEZvTHhQMWJ2aFU5RjZLT3lRNC9YVlNhOUxaS1IKK0Q2Q1JYUlpJSHJ4cjRrV1h0MFJUbHJycDI5WmIzSThKSHFnYkRSc21xTmtNR0l3RGdZRFZSMFBBUUgvQkFRRApBZ1dnTUJNR0ExVWRKUVFNTUFvR0NDc0dBUVVGQndNQk1COEdBMVVkSXdRWU1CYUFGRCtNaXhOTEUvSWJJVFpFCjlyMlViendOUTJjUE1Cb0dBMVVkRVFRVE1CR0NEMnh2WTJGc0xqQjRaR0psTG1SbGRqQUtCZ2dxaGtqT1BRUUQKQWdOSEFEQkVBaUE5SStEcTBPaW9XMTA3RmQwamdCWmpaZFF4NElZWGJiOHFROENTY1NwalpBSWdESjVERllhZwp0aHVRd3V4VEUxeE8wWEFMUDJUcjdNRzlkYmN5MzhmUUk2bz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
          trustore:
            certificate: "base64:LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNMekNDQWRTZ0F3SUJBZ0lSQUt5UkE1MkZrQ1pOQ09jT01qWXJEV3N3Q2dZSUtvWkl6ajBFQXdJd2RURWUKTUJ3R0ExVUVDaE1WYld0alpYSjBJR1JsZG1Wc2IzQnRaVzUwSUVOQk1TVXdJd1lEVlFRTERCeHpZV3QxUUhOaAphM1V0VkdocGJtdFFZV1F0UlRFMExVZGxiaTAzTVN3d0tnWURWUVFERENOdGEyTmxjblFnYzJGcmRVQnpZV3QxCkxWUm9hVzVyVUdGa0xVVXhOQzFIWlc0dE56QWVGdzB5TmpBME1UVXdPVEk0TlRGYUZ3MHpOakEwTVRVd09USTQKTlRGYU1IVXhIakFjQmdOVkJBb1RGVzFyWTJWeWRDQmtaWFpsYkc5d2JXVnVkQ0JEUVRFbE1DTUdBMVVFQ3d3YwpjMkZyZFVCellXdDFMVlJvYVc1clVHRmtMVVV4TkMxSFpXNHROekVzTUNvR0ExVUVBd3dqYld0alpYSjBJSE5oCmEzVkFjMkZyZFMxVWFHbHVhMUJoWkMxRk1UUXRSMlZ1TFRjd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUIKQndOQ0FBVFZvdGdVVWdvRllQRm94VE5TNVNzbEViK21WMFFueGoxdysxODI1SE5vbUNRRFhTSHQralBMUFZMWQo0dTB1aHJwQnZ0TjlzVUVYYW1kZm91bEdmNDlobzBVd1F6QU9CZ05WSFE4QkFmOEVCQU1DQWdRd0VnWURWUjBUCkFRSC9CQWd3QmdFQi93SUJBREFkQmdOVkhRNEVGZ1FVUDR5TEUwc1Q4aHNoTmtUMnZaUnZQQTFEWnc4d0NnWUkKS29aSXpqMEVBd0lEU1FBd1JnSWhBS1d3ZjIvYzRZYUVUNmY3dldDeUExcEYwNUt0QXMvUWprNHdwY1lIY0I3UQpBaUVBZ3orL0tVamNlcEgveWNuVmNlcjN2b21xOVFzZXMwMDMzdXlyNjhscFNmZz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
  # Step 1a: End of SSL configuration

server:
  port: 8443
  # Step 1b: Enable SSL and specify ssl bundle
  ssl:
    bundle: "web"
  # Step 1b: End of SSL configuration
  # Step 5: Configure session cookie with SameSite attribute
  servlet:
    session:
      cookie:
        same-site: strict
  # Step 5: End of session cookie configuration
